databases:
  - name: controle-estoque-db
    databaseName: controle_estoque
    user: controle_user
    plan: free          # PostgreSQL gratuito

services:
  - type: web
    name: controle-estoque
    runtime: php        # <<< mantém
    plan: free

    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      php artisan migrate --force
      npm ci
      npm run build

    startCommand: php artisan serve --host 0.0.0.0 --port $PORT

    envVars:
      - key: APP_ENV
        value: production
      - key: DATABASE_URL          # ligação automática com o DB acima
        fromDatabase:
          name: controle-estoque-db
          property: connectionString