databases:
  - name: controle-estoque-db
    databaseName: controle_estoque
    user: controle_user
    plan: free

services:
  - type: web
    name: controle-estoque
    runtime: docker          # usa o Dockerfile do repositório
    plan: free
    dockerfilePath: ./Dockerfile

    envVars:
      # Laravel / URL
      - key: APP_ENV
        value: production
      - key: APP_URL
        value: https://controle-estoque-te2m.onrender.com
      - key: ASSET_URL
        value: https://controle-estoque-te2m.onrender.com
      - key: APP_DEBUG
        value: "false"

      # Render injeta essa flag automaticamente no container
      - key: RENDER
        value: "true"

      # Conexão PostgreSQL (mapa 1-a-1, sem expor senha no código)
      - key: DATABASE_URL
        fromDatabase:
          name: controle-estoque-db
          property: connectionString
      - key: DB_HOST
        fromDatabase:
          name: controle-estoque-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: controle-estoque-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: controle-estoque-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: controle-estoque-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: controle-estoque-db
          property: password
