databases:
  - name: controle-estoque-db
    databaseName: controle_estoque
    user: controle_user
    plan: free          # PostgreSQL gratuito

services:
  - type: web
    name: controle-estoque
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile   # Render usará este Dockerfile

    envVars:
      - key: APP_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: controle-estoque-db
          property: connectionString